### ISSUE TITLE
Sign in error

### ISSUE THREAD

**Issue by AllisonMadigan** [petersanchez/galerts#1]
Hi Peter,

I'd like to use your galerts package but have not been able to log in. When try to run 

```
import galerts
gam = galerts.GAlertsManager('myemail', 'mypassword') 
```

I get the error 

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Users/AllisonMadigan/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/galerts.py", line 296, in **init**

```
self._signin(password)
```

  File "/Users/AllisonMadigan/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/galerts.py", line 315, in _signin

```
if galx_match_obj.group(1) is not None else ''
```

AttributeError: 'NoneType' object has no attribute 'group'

Am I doing something wrong?

Thank you,
Allison

**Comment by petersanchez** [comment]
Hi Allison,

I apologize. I haven't used this module in some time. I believe the owner made someone else a maintainer. Sorry I wasn't more help.

Peter
